{
  "en_us":{
    "short":"en",
    "flag":"us",
    "complete":"en-US",
    "name":"English",
    "variant":"en-US",
    "free_conversation":"Conversation",
    "job_interview":"Job Interview",
    "choose_subject":"Choose a Custom Subject",
    "choose_language":"Choose Your Language",
    "choose_username":"Enter Your Username",
    "username":"Username",
    "proceed":"Continue",
    "please_enter_username":"Please enter your username.",
    "please_choose_language":"Please select a language.",
    "listening_status":"Listening",
    "wait_status":"Wait...",
    "speaking_status":"Speaking",
    "waiting_your_answer_status":"Waiting your answer",
    "tap_mic":"Tap on the mic to speak...",
    "conversation_history":"My conversation history",
    "manual_mode_text":"Manual Mode",
    "automatic_mode_text":"Automatic Mode",
    "manual_mode_description":"Tap on the mic button on the bottom to speak.",
    "automatic_mode_description":"You can speak now, after that await the response, and start speak again, try that.",
    "messages":"Messages",
    "evaluate_conversation":"Evaluate Conversation",
    "premium_notice":"You need to be a premium user; the evaluations have a cost for us, so it's not possible to use them for free.",
    "see_options":"See options",
    "please_choose_language_to_learn":"The language you are learning at the moment:",
    "learn_according_level":"Learn according to your level",
    "choose_level":"Choose Your Level",
    "select_level_message":"Please select the level you want to learn:",
    "basic_level":"Basic Level",
    "intermediate_level":"Intermediate Level",
    "advanced_level":"Advanced Level",
    "custom_prompt":"Custom Prompt",
    "custom_prompt_description":"Use this to practice everyday situations, like in a bakery, in a restaurant, or any other scenario, specifying as much as possible.",
    "interview_training":"Interview Training",
    "interview_training_description":"Enter the position in the field below, and good practice!",
    "premium_required":"Premium Required",
    "premium_required_message":"You need to be a premium user to access this feature.",
    "fetching_products":"Fetching products...",
    "subscriptions":"Subscriptions",
    "no_cost_option":"No costs option:",
    "free_user_with_ads":"Free user with ads",
    "say_goodbye_to_ads":"Say goodbye to ads! We rely on a small yearly fee to cover server costs and improve your experience.",
    "monthly_price":"Monthly price:",
    "free_trial_description":"5 days free trial, no ads, all features available. You can cancel before the trial ends."
  },
  "pt_br":{
    "short":"pt",
    "flag":"br",
    "complete":"pt-BR",
    "name":"Português",
    "variant":"pt-BR",
    "free_conversation":"Conversar livremente",
    "job_interview":"Entrevista de emprego",
    "choose_subject":"Escolha um tema",
    "choose_language":"Escolha seu idioma",
    "choose_username":"Seu nome",
    "username":"Nome de usuário",
    "proceed":"Continuar",
    "please_enter_username":"Digite o nome de usuário.",
    "please_choose_language":"Selecione o idioma.",
    "listening_status":"Ouvindo",
    "wait_status":"Aguarde...",
    "speaking_status":"Falando",
    "waiting_your_answer_status":"Aguardando sua resposta",
    "tap_mic":"Clique no microfone para falar...",
    "conversation_history":"Meu histórico de conversação",
    "manual_mode_text":"Modo Manual",
    "automatic_mode_text":"Modo Automático",
    "manual_mode_description":"Clique no microfone na parte inferior para falar.",
    "automatic_mode_description":"Você pode falar agora, aguarde a resposta e comece a falar novamente, tente.",
    "messages":"Mensagens",
    "evaluate_conversation":"Avaliar esta conversa",
    "premium_notice":"Você precisa ser um usuário premium; as avaliações têm um custo para nós, então não é possível usá-las gratuitamente.",
    "see_options":"Ver opções",
    "please_choose_language_to_learn":"Qual idioma quer praticar?",
    "learn_according_level":"Aprenda de acordo com seu nível",
    "choose_level":"Escolha seu nível",
    "select_level_message":"Por favor, selecione o nível que deseja aprender:",
    "basic_level":"Nível Básico",
    "intermediate_level":"Nível Intermediário",
    "advanced_level":"Nível Avançado",
    "custom_prompt":"Tema Personalizado",
    "custom_prompt_description":"Use para praticar situações cotidianas, como exemplo: em uma padaria, em um restaurante ou qualquer outro tema, especificando ao máximo.",
    "interview_training":"Treinamento para entrevista",
    "interview_training_description":"Escreva o cargo no campo abaixo, e boa prática!",
    "premium_required":"Requerido Premium",
    "premium_required_message":"Você precisa ser um usuário premium para acessar este recurso.",
    "fetching_products":"Buscando produtos...",
    "subscriptions":"Assinaturas",
    "no_cost_option":"Opção sem custos:",
    "free_user_with_ads":"Usuário gratuito com anúncios",
    "say_goodbye_to_ads":"Diga adeus aos anúncios! Contamos com uma pequena taxa anual para cobrir os custos do servidor e melhorar sua experiência.",
    "monthly_price":"Preço mensal:",
    "free_trial_description":"5 dias de teste grátis, sem anúncios, todos os recursos disponíveis. Você pode cancelar antes que o teste termine."
  },
  "de_de":{
    "short":"de",
    "flag":"de",
    "complete":"de-DE",
    "name":"Deutsch",
    "variant":"de-DE",
    "free_conversation":"Konversation",
    "job_interview":"Bewerbungsgespräch",
    "choose_subject":"Thema auswählen",
    "choose_language":"Wählen Sie Ihre Sprache",
    "choose_username":"Geben Sie Ihren Benutzernamen ein",
    "username":"Benutzername",
    "proceed":"Fortfahren",
    "please_enter_username":"Bitte geben Sie Ihren Benutzernamen ein.",
    "please_choose_language":"Bitte wählen Sie eine Sprache.",
    "listening_status":"Hören",
    "wait_status":"Warten...",
    "speaking_status":"Sprechen",
    "waiting_your_answer_status":"Warten auf Ihre Antwort",
    "tap_mic":"Tippen Sie auf das Mikrofon, um zu sprechen...",
    "conversation_history":"Mein Gesprächsverlauf",
    "manual_mode_text":"Manueller Modus",
    "automatic_mode_text":"Automatischer Modus",
    "manual_mode_description":"Tippen Sie unten auf die Mikrofontaste, um zu sprechen.",
    "automatic_mode_description":"Sie können jetzt sprechen, warten Sie auf die Antwort und sprechen Sie erneut.",
    "messages":"Nachrichten",
    "evaluate_conversation":"Gespräch bewerten",
    "premium_notice":"Sie müssen ein Premium-Benutzer sein; die Bewertungen kosten uns etwas, daher ist es nicht möglich, sie kostenlos zu nutzen.",
    "see_options":"Optionen anzeigen",
    "please_choose_language_to_learn":"Die Sprache, die Sie momentan lernen:",
    "learn_according_level":"Lernen Sie entsprechend Ihrem Niveau",
    "choose_level":"Wählen Sie Ihr Niveau",
    "select_level_message":"Bitte wählen Sie das Niveau, das Sie lernen möchten:",
    "basic_level":"Grundstufe",
    "intermediate_level":"Mittelstufe",
    "advanced_level":"Fortgeschrittenes Niveau",
    "custom_prompt":"Benutzerdefiniertes Thema",
    "custom_prompt_description":"Verwenden Sie dies, um alltägliche Situationen zu üben, z. B. in einer Bäckerei, in einem Restaurant oder in einem anderen Szenario, so genau wie möglich spezifizieren.",
    "interview_training":"Interview Training",
    "interview_training_description":"Geben Sie die Position in das unten stehende Feld ein und viel Spaß beim Üben!",
    "premium_required":"Premium erforderlich",
    "premium_required_message":"Sie müssen ein Premium-Benutzer sein, um auf diese Funktion zuzugreifen.",
    "fetching_products":"Produkte werden abgerufen...",
    "subscriptions":"Abonnements",
    "no_cost_option":"Kostenlose Option:",
    "free_user_with_ads":"Kostenloser Benutzer mit Werbung",
    "say_goodbye_to_ads":"Verabschieden Sie sich von Werbung! Wir sind auf eine kleine jährliche Gebühr angewiesen, um die Serverkosten zu decken und Ihr Erlebnis zu verbessern.",
    "monthly_price":"Monatlicher Preis:",
    "free_trial_description":"5 Tage kostenlos testen, keine Werbung, alle Funktionen verfügbar. Sie können vor Ablauf des Testzeitraums kündigen."
  },
  "hi_in":{
    "short":"hi",
    "flag":"in",
    "complete":"hi-IN",
    "name":"हिन्दी",
    "variant":"hi-IN",
    "free_conversation":"वार्तालाप",
    "job_interview":"नौकरी का साक्षात्कार",
    "choose_subject":"विषय चुनें",
    "choose_language":"अपनी भाषा चुनें",
    "choose_username":"अपना उपयोगकर्ता नाम दर्ज करें",
    "username":"उपयोगकर्ता नाम",
    "proceed":"जारी रखें",
    "please_enter_username":"कृपया अपना उपयोगकर्ता नाम दर्ज करें।",
    "please_choose_language":"कृपया एक भाषा चुनें।",
    "listening_status":"सुन रहे हैं",
    "wait_status":"प्रतीक्षा करें...",
    "speaking_status":"बोल रहे हैं",
    "waiting_your_answer_status":"आपके उत्तर की प्रतीक्षा कर रहे हैं",
    "tap_mic":"बोलने के लिए माइक्रोफ़ोन पर टैप करें...",
    "conversation_history":"मेरी वार्तालाप इतिहास",
    "manual_mode_text":"मैनुअल मोड",
    "automatic_mode_text":"स्वचालित मोड",
    "manual_mode_description":"बोलने के लिए नीचे माइक्रोफ़ोन बटन पर टैप करें।",
    "automatic_mode_description":"आप अब बोल सकते हैं, उत्तर की प्रतीक्षा करें और फिर से बोलें।",
    "messages":"संदेश",
    "evaluate_conversation":"वार्तालाप का मूल्यांकन करें",
    "premium_notice":"आपको एक प्रीमियम उपयोगकर्ता होना चाहिए; मूल्यांकन के लिए हमें लागत आती है, इसलिए उन्हें मुफ्त में उपयोग करना संभव नहीं है।",
    "see_options":"विकल्प देखें",
    "please_choose_language_to_learn":"वह भाषा जिसे आप अभी सीख रहे हैं:",
    "learn_according_level":"अपने स्तर के अनुसार सीखें",
    "choose_level":"अपना स्तर चुनें",
    "select_level_message":"कृपया वह स्तर चुनें जिसे आप सीखना चाहते हैं:",
    "basic_level":"बुनियादी स्तर",
    "intermediate_level":"मध्यम स्तर",
    "advanced_level":"उन्नत स्तर",
    "custom_prompt":"कस्टम प्रॉम्प्ट",
    "custom_prompt_description":"इसका उपयोग रोजमर्रा की स्थितियों का अभ्यास करने के लिए करें, जैसे बेकरी में, रेस्तरां में, या किसी अन्य स्थिति में, जितना हो सके विशिष्ट करें।",
    "interview_training":"इंटरव्यू प्रशिक्षण",
    "interview_training_description":"नीचे दिए गए क्षेत्र में पद दर्ज करें, और शुभकामनाएँ!",
    "premium_required":"प्रीमियम आवश्यक",
    "premium_required_message":"इस सुविधा का उपयोग करने के लिए आपको प्रीमियम उपयोगकर्ता होना चाहिए।",
    "fetching_products":"उत्पाद प्राप्त किए जा रहे हैं...",
    "subscriptions":"सदस्यता",
    "no_cost_option":"कोई लागत विकल्प नहीं:",
    "free_user_with_ads":"विज्ञापनों के साथ मुफ्त उपयोगकर्ता",
    "say_goodbye_to_ads":"विज्ञापनों को अलविदा कहें! सर्वर लागत को कवर करने और आपके अनुभव को बेहतर बनाने के लिए हम एक छोटी वार्षिक शुल्क पर निर्भर हैं।",
    "monthly_price":"मासिक मूल्य:",
    "free_trial_description":"5 दिन का मुफ्त परीक्षण, कोई विज्ञापन नहीं, सभी सुविधाएँ उपलब्ध। आप परीक्षण समाप्त होने से पहले रद्द कर सकते हैं।"
  },
  "es_es":{
    "short":"es",
    "flag":"es",
    "complete":"es-ES",
    "name":"Español",
    "variant":"es-ES",
    "free_conversation":"Conversación",
    "job_interview":"Entrevista de trabajo",
    "choose_subject":"Elige un tema",
    "choose_language":"Elige tu idioma",
    "choose_username":"Ingrese su nombre de usuario",
    "username":"Nombre de usuario",
    "proceed":"Continuar",
    "please_enter_username":"Por favor, ingrese su nombre de usuario.",
    "please_choose_language":"Por favor seleccione un idioma.",
    "listening_status":"Escuchando",
    "wait_status":"Esperar...",
    "speaking_status":"Hablando",
    "waiting_your_answer_status":"Esperando tu respuesta",
    "tap_mic":"Toca el micrófono para hablar...",
    "conversation_history":"Mi historial de conversaciones",
    "manual_mode_text":"Modo Manual",
    "automatic_mode_text":"Modo Automático",
    "manual_mode_description":"Toque el botón del micrófono en la parte inferior para hablar.",
    "automatic_mode_description":"Puedes hablar ahora, espera la respuesta y vuelve a hablar.",
    "messages":"Mensajes",
    "evaluate_conversation":"Evaluar conversación",
    "premium_notice":"Necesitas ser un usuario premium; las evaluaciones tienen un costo para nosotros, por lo que no es posible usarlas de forma gratuita.",
    "see_options":"Ver opciones",
    "please_choose_language_to_learn":"El idioma que estás aprendiendo en este momento:",
    "learn_according_level":"Aprende según tu nivel",
    "choose_level":"Elige tu nivel",
    "select_level_message":"Por favor, selecciona el nivel que deseas aprender:",
    "basic_level":"Nivel Básico",
    "intermediate_level":"Nivel Intermedio",
    "advanced_level":"Nivel Avanzado",
    "custom_prompt":"Tema Personalizado",
    "custom_prompt_description":"Usa esto para practicar situaciones cotidianas, como en una panadería, en un restaurante, o cualquier otro escenario, especificando lo máximo posible.",
    "interview_training":"Entrenamiento de Entrevista",
    "interview_training_description":"Ingrese el puesto en el campo a continuación, ¡y buena práctica!",
    "premium_required":"Se requiere premium",
    "premium_required_message":"Necesitas ser un usuario premium para acceder a esta función.",
    "fetching_products":"Obteniendo productos...",
    "subscriptions":"Suscripciones",
    "no_cost_option":"Opción sin costos:",
    "free_user_with_ads":"Usuario gratuito con anuncios",
    "say_goodbye_to_ads":"¡Despídete de los anuncios! Dependemos de una pequeña tarifa anual para cubrir los costos del servidor y mejorar tu experiencia.",
    "monthly_price":"Precio mensual:",
    "free_trial_description":"5 días de prueba gratuita, sin anuncios, todas las funciones disponibles. Puedes cancelar antes de que finalice la prueba."
  },
  "uk_ua":{
    "short":"uk",
    "flag":"ua",
    "complete":"uk-UA",
    "name":"Українська",
    "variant":"uk-UA",
    "free_conversation":"Розмова",
    "job_interview":"Співбесіда",
    "choose_subject":"Виберіть тему",
    "choose_language":"Виберіть мову",
    "choose_username":"Введіть своє ім'я користувача",
    "username":"Ім'я користувача",
    "proceed":"Продовжити",
    "please_enter_username":"Будь ласка, введіть своє ім'я користувача.",
    "please_choose_language":"Будь ласка, виберіть мову.",
    "listening_status":"Слухання",
    "wait_status":"Зачекайте...",
    "speaking_status":"Говоріння",
    "waiting_your_answer_status":"Очікування вашої відповіді",
    "tap_mic":"Натисніть на мікрофон, щоб говорити...",
    "conversation_history":"Історія розмов",
    "manual_mode_text":"Ручний режим",
    "automatic_mode_text":"Автоматичний режим",
    "manual_mode_description":"Натисніть кнопку мікрофона внизу, щоб говорити.",
    "automatic_mode_description":"Ви можете говорити зараз, зачекайте на відповідь і знову починайте говорити.",
    "messages":"Повідомлення",
    "evaluate_conversation":"Оцінити розмову",
    "premium_notice":"Ви повинні бути преміум-користувачем; оцінювання для нас коштує, тому не можна використовувати їх безкоштовно.",
    "see_options":"Подивитися варіанти",
    "please_choose_language_to_learn":"Мова, яку ви зараз вивчаєте:",
    "learn_according_level":"Вчіться відповідно до свого рівня",
    "choose_level":"Виберіть свій рівень",
    "select_level_message":"Будь ласка, виберіть рівень, який ви хочете вивчати:",
    "basic_level":"Базовий рівень",
    "intermediate_level":"Середній рівень",
    "advanced_level":"Просунутий рівень",
    "custom_prompt":"Користувацька тема",
    "custom_prompt_description":"Використовуйте це для практики повсякденних ситуацій, наприклад, у пекарні, ресторані або іншому сценарії, максимально конкретизуючи.",
    "interview_training":"Навчання на співбесіду",
    "interview_training_description":"Введіть посаду в поле нижче і гарної практики!",
    "premium_required":"Потрібен преміум",
    "premium_required_message":"Ви повинні бути преміум-користувачем, щоб отримати доступ до цієї функції.",
    "fetching_products":"Отримання продуктів...",
    "subscriptions":"Підписки",
    "no_cost_option":"Безкоштовний варіант:",
    "free_user_with_ads":"Безкоштовний користувач з рекламою",
    "say_goodbye_to_ads":"Скажіть прощай рекламі! Ми покладаємося на невелику річну плату, щоб покрити витрати на сервер і покращити ваш досвід.",
    "monthly_price":"Місячна ціна:",
    "free_trial_description":"5 днів безкоштовного пробного періоду, без реклами, доступні всі функції. Ви можете скасувати до закінчення пробного періоду."
  },
  "ru_ru":{
    "short":"ru",
    "flag":"ru",
    "complete":"ru-RU",
    "name":"Русский",
    "variant":"ru-RU",
    "free_conversation":"Разговор",
    "job_interview":"Собеседование",
    "choose_subject":"Выберите тему",
    "choose_language":"Выберите ваш язык",
    "choose_username":"Введите ваше имя пользователя",
    "username":"Имя пользователя",
    "proceed":"Продолжить",
    "please_enter_username":"Пожалуйста, введите ваше имя пользователя.",
    "please_choose_language":"Пожалуйста, выберите язык.",
    "listening_status":"Прослушивание",
    "wait_status":"Подождите...",
    "speaking_status":"Говорение",
    "waiting_your_answer_status":"Ожидание вашего ответа",
    "tap_mic":"Нажмите на микрофон, чтобы говорить...",
    "conversation_history":"История разговоров",
    "manual_mode_text":"Ручной режим",
    "automatic_mode_text":"Автоматический режим",
    "manual_mode_description":"Нажмите кнопку микрофона внизу, чтобы говорить.",
    "automatic_mode_description":"Вы можете говорить сейчас, подождите ответ и снова начните говорить.",
    "messages":"Сообщения",
    "evaluate_conversation":"Оценить разговор",
    "premium_notice":"Вы должны быть премиум-пользователем; оценки стоят для нас дорого, поэтому невозможно использовать их бесплатно.",
    "see_options":"Смотреть варианты",
    "please_choose_language_to_learn":"Язык, который вы сейчас учите:",
    "learn_according_level":"Учитесь в соответствии с вашим уровнем",
    "choose_level":"Выберите свой уровень",
    "select_level_message":"Пожалуйста, выберите уровень, который хотите изучать:",
    "basic_level":"Базовый уровень",
    "intermediate_level":"Средний уровень",
    "advanced_level":"Продвинутый уровень",
    "custom_prompt":"Пользовательская тема",
    "custom_prompt_description":"Используйте это для практики повседневных ситуаций, например, в пекарне, в ресторане или в любом другом сценарии, максимально уточняя.",
    "interview_training":"Тренировка интервью",
    "interview_training_description":"Введите должность в поле ниже, и удачной практики!",
    "premium_required":"Требуется премиум",
    "premium_required_message":"Вам нужно быть премиум-пользователем, чтобы получить доступ к этой функции.",
    "fetching_products":"Получение продуктов...",
    "subscriptions":"Подписки",
    "no_cost_option":"Бесплатный вариант:",
    "free_user_with_ads":"Бесплатный пользователь с рекламой",
    "say_goodbye_to_ads":"Скажите прощай рекламе! Мы полагаемся на небольшую ежегодную плату, чтобы покрыть расходы на сервер и улучшить ваш опыт.",
    "monthly_price":"Месячная цена:",
    "free_trial_description":"5 дней бесплатной пробной версии, без рекламы, все функции доступны. Вы можете отменить до окончания пробного периода."
  },
  "zh_cn":{
    "short":"zh",
    "flag":"cn",
    "complete":"zh-CN",
    "name":"中文",
    "variant":"zh-CN",
    "free_conversation":"对话",
    "job_interview":"工作面试",
    "choose_subject":"选择一个主题",
    "choose_language":"选择你的语言",
    "choose_username":"输入您的用户名",
    "username":"用户名",
    "proceed":"继续",
    "please_enter_username":"请输入您的用户名。",
    "please_choose_language":"请选择一种语言。",
    "listening_status":"正在听",
    "wait_status":"等待...",
    "speaking_status":"说话",
    "waiting_your_answer_status":"等待您的回答",
    "tap_mic":"点击麦克风说话...",
    "conversation_history":"我的对话历史",
    "manual_mode_text":"手动模式",
    "automatic_mode_text":"自动模式",
    "manual_mode_description":"点击下方的麦克风按钮开始说话。",
    "automatic_mode_description":"您现在可以说话，等待回答，然后再次说话。",
    "messages":"消息",
    "evaluate_conversation":"评估对话",
    "premium_notice":"您需要成为高级用户；评估对我们来说是有成本的，因此无法免费使用。",
    "see_options":"查看选项",
    "please_choose_language_to_learn":"您目前正在学习的语言：",
    "learn_according_level":"根据你的水平学习",
    "choose_level":"选择您的水平",
    "select_level_message":"请选择您想要学习的级别：",
    "basic_level":"基础水平",
    "intermediate_level":"中级水平",
    "advanced_level":"高级水平",
    "custom_prompt":"自定义提示",
    "custom_prompt_description":"使用这个来练习日常情况，比如在面包店、餐馆或任何其他场景中，尽可能详细地说明。",
    "interview_training":"面试培训",
    "interview_training_description":"在下面的字段中输入职位，祝您练习愉快！",
    "premium_required":"需要高级版",
    "premium_required_message":"您需要成为高级用户才能使用此功能。",
    "fetching_products":"获取产品中...",
    "subscriptions":"订阅",
    "no_cost_option":"无成本选项：",
    "free_user_with_ads":"带广告的免费用户",
    "say_goodbye_to_ads":"告别广告！我们依靠一小笔年费来支付服务器成本并改善您的体验。",
    "monthly_price":"月费：",
    "free_trial_description":"5天免费试用，无广告，所有功能可用。您可以在试用结束前取消。"
  },
  "ja_jp":{
    "short":"ja",
    "flag":"jp",
    "complete":"ja-JP",
    "name":"日本語",
    "variant":"ja-JP",
    "free_conversation":"会話",
    "job_interview":"面接",
    "choose_subject":"テーマを選択",
    "choose_language":"言語を選択",
    "choose_username":"ユーザー名を入力してください",
    "username":"ユーザー名",
    "proceed":"続行",
    "please_enter_username":"ユーザー名を入力してください。",
    "please_choose_language":"言語を選択してください。",
    "listening_status":"リスニング",
    "wait_status":"お待ちください...",
    "speaking_status":"話している",
    "waiting_your_answer_status":"回答を待っています",
    "tap_mic":"話すにはマイクをタップしてください...",
    "conversation_history":"会話履歴",
    "manual_mode_text":"手動モード",
    "automatic_mode_text":"自動モード",
    "manual_mode_description":"下のマイクボタンをタップして話します。",
    "automatic_mode_description":"今話しても大丈夫です。応答を待って、再び話し始めてください。",
    "messages":"メッセージ",
    "evaluate_conversation":"会話を評価する",
    "premium_notice":"プレミアムユーザーである必要があります。評価にはコストがかかるため、無料で使用することはできません。",
    "see_options":"オプションを見る",
    "please_choose_language_to_learn":"現在学習している言語：",
    "learn_according_level":"あなたのレベルに応じて学ぶ",
    "choose_level":"レベルを選択",
    "select_level_message":"学びたいレベルを選択してください：",
    "basic_level":"基本レベル",
    "intermediate_level":"中級レベル",
    "advanced_level":"上級レベル",
    "custom_prompt":"カスタムプロンプト",
    "custom_prompt_description":"ベーカリーやレストランなど、日常のシチュエーションを練習するために使用し、できるだけ具体的に指定してください。",
    "interview_training":"面接トレーニング",
    "interview_training_description":"下のフィールドに役職を入力して、練習を楽しんでください！",
    "premium_required":"プレミアムが必要",
    "premium_required_message":"この機能にアクセスするには、プレミアムユーザーである必要があります。",
    "fetching_products":"商品を取得しています...",
    "subscriptions":"サブスクリプション",
    "no_cost_option":"コストなしのオプション：",
    "free_user_with_ads":"広告付きの無料ユーザー",
    "say_goodbye_to_ads":"広告にさようなら！サーバーコストをカバーし、体験を向上させるために少額の年会費を頼りにしています。",
    "monthly_price":"月額料金：",
    "free_trial_description":"5日間の無料トライアル、広告なし、すべての機能が利用可能です。試用期間が終了する前にキャンセルできます。"
  },
  "ur_pk":{
    "short":"ur",
    "flag":"pk",
    "complete":"ur-PK",
    "name":"اردو",
    "variant":"ur-PK",
    "free_conversation":"گفتگو",
    "job_interview":"ملازمت کا انٹرویو",
    "choose_subject":"موضوع منتخب کریں",
    "choose_language":"اپنی زبان کا انتخاب کریں",
    "choose_username":"اپنا صارف نام درج کریں",
    "username":"صارف کا نام",
    "proceed":"جاری رکھیں",
    "please_enter_username":"براہ کرم اپنا صارف نام درج کریں۔",
    "please_choose_language":"براہ کرم ایک زبان منتخب کریں۔",
    "listening_status":"سن رہا ہے",
    "wait_status":"انتظار کریں...",
    "speaking_status":"بول رہا ہے",
    "waiting_your_answer_status":"آپ کے جواب کا انتظار ہے",
    "tap_mic":"بولنے کے لئے مائک پر ٹیپ کریں...",
    "conversation_history":"میری گفتگو کی تاریخ",
    "manual_mode_text":"دستی موڈ",
    "automatic_mode_text":"خودکار موڈ",
    "manual_mode_description":"بات کرنے کے لئے نیچے مائیکروفون بٹن پر ٹیپ کریں۔",
    "automatic_mode_description":"آپ اب بول سکتے ہیں، جواب کا انتظار کریں اور دوبارہ بولنا شروع کریں۔",
    "messages":"پیغامات",
    "evaluate_conversation":"گفتگو کی تشخیص کریں",
    "premium_notice":"آپ کو ایک پریمیم صارف ہونا چاہئے۔ تشخیصات ہمارے لئے ایک قیمت رکھتے ہیں، اس لئے ان کا مفت استعمال ممکن نہیں ہے۔",
    "see_options":"اختیارات دیکھیں",
    "please_choose_language_to_learn":"وہ زبان جو آپ اس وقت سیکھ رہے ہیں:",
    "learn_according_level":"اپنے لیول کے مطابق سیکھیں",
    "choose_level":"اپنا لیول منتخب کریں",
    "select_level_message":"براہ کرم وہ سطح منتخب کریں جو آپ سیکھنا چاہتے ہیں:",
    "basic_level":"بنیادی سطح",
    "intermediate_level":"درمیانی سطح",
    "advanced_level":"اعلیٰ سطح",
    "custom_prompt":"حسب ضرورت پرامپٹ",
    "custom_prompt_description":"اس کا استعمال روزمرہ کے حالات کی مشق کے لیے کریں، جیسے بیکری میں، ریستوراں میں، یا کسی دوسرے منظر نامے میں، جتنا ممکن ہو سکے مخصوص کریں۔",
    "interview_training":"انٹرویو کی تربیت",
    "interview_training_description":"نیچے دیئے گئے فیلڈ میں پوزیشن درج کریں، اور اچھی مشق کریں!",
    "premium_required":"پریمیم ضروری ہے",
    "premium_required_message":"اس فیچر تک رسائی کے لیے آپ کو پریمیم صارف ہونا ضروری ہے۔",
    "fetching_products":"مصنوعات لائی جارہی ہیں...",
    "subscriptions":"سبسکرپشنز",
    "no_cost_option":"بغیر کسی قیمت کا آپشن:",
    "free_user_with_ads":"اشتہارات کے ساتھ مفت صارف",
    "say_goodbye_to_ads":"اشتہارات کو الوداع کہیں! سرور کے اخراجات کو پورا کرنے اور آپ کے تجربے کو بہتر بنانے کے لیے ہم ایک چھوٹی سالانہ فیس پر انحصار کرتے ہیں۔",
    "monthly_price":"ماہانہ قیمت:",
    "free_trial_description":"5 دن کی مفت آزمائش، کوئی اشتہار نہیں، تمام خصوصیات دستیاب ہیں۔ آپ آزمائش کے ختم ہونے سے پہلے منسوخ کر سکتے ہیں۔"
  },
  "fr_fr":{
    "short":"fr",
    "flag":"fr",
    "complete":"fr-FR",
    "name":"Français",
    "variant":"fr-FR",
    "free_conversation":"Conversation",
    "job_interview":"Entretien d'embauche",
    "choose_subject":"Choisissez un sujet",
    "choose_language":"Choisissez votre langue",
    "choose_username":"Entrez votre nom d'utilisateur",
    "username":"Nom d'utilisateur",
    "proceed":"Continuer",
    "please_enter_username":"Veuillez entrer votre nom d'utilisateur.",
    "please_choose_language":"Veuillez sélectionner une langue.",
    "listening_status":"Écoute",
    "wait_status":"Attendez...",
    "speaking_status":"Parler",
    "waiting_your_answer_status":"En attente de votre réponse",
    "tap_mic":"Appuyez sur le micro pour parler...",
    "conversation_history":"Mon historique de conversation",
    "manual_mode_text":"Mode manuel",
    "automatic_mode_text":"Mode automatique",
    "manual_mode_description":"Appuyez sur le bouton du micro en bas pour parler.",
    "automatic_mode_description":"Vous pouvez parler maintenant, attendez la réponse, puis recommencez à parler.",
    "messages":"Messages",
    "evaluate_conversation":"Évaluer la conversation",
    "premium_notice":"Vous devez être un utilisateur premium ; les évaluations ont un coût pour nous, il n'est donc pas possible de les utiliser gratuitement.",
    "see_options":"Voir les options",
    "please_choose_language_to_learn":"La langue que vous apprenez en ce moment :",
    "learn_according_level":"Apprenez selon votre niveau",
    "choose_level":"Choisissez votre niveau",
    "select_level_message":"Veuillez sélectionner le niveau que vous souhaitez apprendre :",
    "basic_level":"Niveau de base",
    "intermediate_level":"Niveau intermédiaire",
    "advanced_level":"Niveau avancé",
    "custom_prompt":"Invite personnalisée",
    "custom_prompt_description":"Utilisez cela pour pratiquer des situations quotidiennes, comme dans une boulangerie, dans un restaurant ou dans tout autre scénario, en spécifiant autant que possible.",
    "interview_training":"Formation à l'entretien",
    "interview_training_description":"Entrez le poste dans le champ ci-dessous, et bonne pratique !",
    "premium_required":"Premium requis",
    "premium_required_message":"Vous devez être un utilisateur premium pour accéder à cette fonctionnalité.",
    "fetching_products":"Récupération des produits...",
    "subscriptions":"Abonnements",
    "no_cost_option":"Option sans coût:",
    "free_user_with_ads":"Utilisateur gratuit avec publicités",
    "say_goodbye_to_ads":"Dites adieu aux publicités! Nous comptons sur une petite redevance annuelle pour couvrir les coûts des serveurs et améliorer votre expérience.",
    "monthly_price":"Prix mensuel:",
    "free_trial_description":"5 jours d'essai gratuit, pas de publicités, toutes les fonctionnalités disponibles. Vous pouvez annuler avant la fin de l'essai."
  },
  "it_it":{
    "short":"it",
    "flag":"it",
    "complete":"it-IT",
    "name":"Italiano",
    "variant":"it-IT",
    "free_conversation":"Conversazione",
    "job_interview":"Colloquio di lavoro",
    "choose_subject":"Scegli un argomento",
    "choose_language":"Scegli la tua lingua",
    "choose_username":"Inserisci il tuo nome utente",
    "username":"Nome utente",
    "proceed":"Continua",
    "please_enter_username":"Per favore, inserisci il tuo nome utente.",
    "please_choose_language":"Si prega di selezionare una lingua.",
    "listening_status":"Ascolto",
    "wait_status":"Attendere...",
    "speaking_status":"Parlare",
    "waiting_your_answer_status":"In attesa della tua risposta",
    "tap_mic":"Tocca il microfono per parlare...",
    "conversation_history":"La mia cronologia delle conversazioni",
    "manual_mode_text":"Modalità manuale",
    "automatic_mode_text":"Modalità automatica",
    "manual_mode_description":"Tocca il pulsante del microfono in basso per parlare.",
    "automatic_mode_description":"Puoi parlare ora, attendi la risposta, quindi ricomincia a parlare.",
    "messages":"Messaggi",
    "evaluate_conversation":"Valuta la conversazione",
    "premium_notice":"Devi essere un utente premium; le valutazioni hanno un costo per noi, quindi non è possibile utilizzarle gratuitamente.",
    "see_options":"Vedi opzioni",
    "please_choose_language_to_learn":"La lingua che stai imparando in questo momento:",
    "learn_according_level":"Impara in base al tuo livello",
    "choose_level":"Scegli il tuo livello",
    "select_level_message":"Si prega di selezionare il livello che si desidera apprendere:",
    "basic_level":"Livello base",
    "intermediate_level":"Livello intermedio",
    "advanced_level":"Livello avanzato",
    "custom_prompt":"Prompt personalizzato",
    "custom_prompt_description":"Usa questo per praticare situazioni quotidiane, come in una panetteria, in un ristorante o in qualsiasi altro scenario, specificando il più possibile.",
    "interview_training":"Formazione all'intervista",
    "interview_training_description":"Inserisci la posizione nel campo sottostante, e buona pratica!",
    "premium_required":"Premium richiesto",
    "premium_required_message":"Devi essere un utente premium per accedere a questa funzione.",
    "fetching_products":"Recupero dei prodotti...",
    "subscriptions":"Abbonamenti",
    "no_cost_option":"Opzione senza costi:",
    "free_user_with_ads":"Utente gratuito con pubblicità",
    "say_goodbye_to_ads":"Dì addio agli annunci! Facciamo affidamento su una piccola tassa annuale per coprire i costi del server e migliorare la tua esperienza.",
    "monthly_price":"Prezzo mensile:",
    "free_trial_description":"5 giorni di prova gratuita, senza pubblicità, tutte le funzionalità disponibili. Puoi annullare prima della fine della prova."
  },
  "nl_nl":{
    "short":"nl",
    "flag":"nl",
    "complete":"nl-NL",
    "name":"Nederlands",
    "variant":"nl-NL",
    "free_conversation":"Gesprek",
    "job_interview":"Sollicitatiegesprek",
    "choose_subject":"Kies een onderwerp",
    "choose_language":"Kies je taal",
    "choose_username":"Voer je gebruikersnaam in",
    "username":"Gebruikersnaam",
    "proceed":"Doorgaan",
    "please_enter_username":"Voer je gebruikersnaam in.",
    "please_choose_language":"Selecteer een taal.",
    "listening_status":"Luisteren",
    "wait_status":"Wachten...",
    "speaking_status":"Spreken",
    "waiting_your_answer_status":"Wachten op je antwoord",
    "tap_mic":"Tik op de microfoon om te spreken...",
    "conversation_history":"Mijn gespreksgeschiedenis",
    "manual_mode_text":"Handmatige modus",
    "automatic_mode_text":"Automatische modus",
    "manual_mode_description":"Tik op de microfoonknop onderaan om te spreken.",
    "automatic_mode_description":"Je kunt nu spreken, wacht op het antwoord en begin opnieuw te spreken.",
    "messages":"Berichten",
    "evaluate_conversation":"Gesprek beoordelen",
    "premium_notice":"Je moet een premiumgebruiker zijn; de evaluaties kosten ons iets, dus het is niet mogelijk om ze gratis te gebruiken.",
    "see_options":"Bekijk opties",
    "please_choose_language_to_learn":"De taal die je momenteel leert:",
    "learn_according_level":"Leer volgens je niveau",
    "choose_level":"Kies je niveau",
    "select_level_message":"Selecteer het niveau dat je wilt leren:",
    "basic_level":"Basisniveau",
    "intermediate_level":"Gemiddeld niveau",
    "advanced_level":"Gevorderd niveau",
    "custom_prompt":"Aangepaste prompt",
    "custom_prompt_description":"Gebruik dit om alledaagse situaties te oefenen, zoals in een bakkerij, in een restaurant of in een ander scenario, zo specifiek mogelijk.",
    "interview_training":"Interviewtraining",
    "interview_training_description":"Voer de positie in het onderstaande veld in, en veel oefenplezier!",
    "premium_required":"Premium vereist",
    "premium_required_message":"Je moet een premiumgebruiker zijn om toegang te krijgen tot deze functie.",
    "fetching_products":"Producten ophalen...",
    "subscriptions":"Abonnementen",
    "no_cost_option":"Geen kostenoptie:",
    "free_user_with_ads":"Gratis gebruiker met advertenties",
    "say_goodbye_to_ads":"Zeg vaarwel tegen advertenties! We rekenen op een kleine jaarlijkse vergoeding om de serverkosten te dekken en je ervaring te verbeteren.",
    "monthly_price":"Maandelijkse prijs:",
    "free_trial_description":"5 dagen gratis proefversie, geen advertenties, alle functies beschikbaar. U kunt annuleren voordat de proefperiode afloopt."
  },
  "sv_se":{
    "short":"sv",
    "flag":"se",
    "complete":"sv-SE",
    "name":"Svenska",
    "variant":"sv-SE",
    "free_conversation":"Konversation",
    "job_interview":"Anställningsintervju",
    "choose_subject":"Välj ett ämne",
    "choose_language":"Välj ditt språk",
    "choose_username":"Ange ditt användarnamn",
    "username":"Användarnamn",
    "proceed":"Fortsätt",
    "please_enter_username":"Vänligen ange ditt användarnamn.",
    "please_choose_language":"Välj ett språk.",
    "listening_status":"Lyssnar",
    "wait_status":"Vänta...",
    "speaking_status":"Talar",
    "waiting_your_answer_status":"Väntar på ditt svar",
    "tap_mic":"Tryck på mikrofonen för att tala...",
    "conversation_history":"Min samtalshistorik",
    "manual_mode_text":"Manuellt läge",
    "automatic_mode_text":"Automatiskt läge",
    "manual_mode_description":"Tryck på mikrofonknappen längst ner för att tala.",
    "automatic_mode_description":"Du kan prata nu, vänta på svar och börja sedan prata igen.",
    "messages":"Meddelanden",
    "evaluate_conversation":"Utvärdera samtalet",
    "premium_notice":"Du måste vara en premiumanvändare; utvärderingarna kostar oss något, så det är inte möjligt att använda dem gratis.",
    "see_options":"Visa alternativ",
    "please_choose_language_to_learn":"Språket du lär dig just nu:",
    "learn_according_level":"Lär dig enligt din nivå",
    "choose_level":"Välj din nivå",
    "select_level_message":"Vänligen välj den nivå du vill lära dig:",
    "basic_level":"Grundnivå",
    "intermediate_level":"Mellannivå",
    "advanced_level":"Avancerad nivå",
    "custom_prompt":"Anpassad prompt",
    "custom_prompt_description":"Använd detta för att öva på vardagssituationer, som i ett bageri, på en restaurang eller i något annat scenario, specificera så mycket som möjligt.",
    "interview_training":"Intervjuträning",
    "interview_training_description":"Ange positionen i fältet nedan, och lycka till med övningen!",
    "premium_required":"Premium krävs",
    "premium_required_message":"Du måste vara en premiumanvändare för att få tillgång till den här funktionen.",
    "fetching_products":"Hämtar produkter...",
    "subscriptions":"Prenumerationer",
    "no_cost_option":"Inga kostnader:",
    "free_user_with_ads":"Gratis användare med annonser",
    "say_goodbye_to_ads":"Säg adjö till annonser! Vi förlitar oss på en liten årlig avgift för att täcka serverkostnader och förbättra din upplevelse.",
    "monthly_price":"Månadspris:",
    "free_trial_description":"5 dagars gratis provperiod, inga annonser, alla funktioner tillgängliga. Du kan avbryta innan provperioden löper ut."
  },
  "el_gr":{
    "short":"el",
    "flag":"gr",
    "complete":"el-GR",
    "name":"Ελληνικά",
    "variant":"el-GR",
    "free_conversation":"Συνομιλία",
    "job_interview":"Συνέντευξη για δουλειά",
    "choose_subject":"Επιλέξτε θέμα",
    "choose_language":"Επιλέξτε τη γλώσσα σας",
    "choose_username":"Εισάγετε το όνομα χρήστη σας",
    "username":"Όνομα χρήστη",
    "proceed":"Συνέχεια",
    "please_enter_username":"Παρακαλώ εισάγετε το όνομα χρήστη σας.",
    "please_choose_language":"Παρακαλώ επιλέξτε γλώσσα.",
    "listening_status":"Ακρόαση",
    "wait_status":"Περιμένετε...",
    "speaking_status":"Ομιλία",
    "waiting_your_answer_status":"Αναμονή για την απάντησή σας",
    "tap_mic":"Πατήστε το μικρόφωνο για να μιλήσετε...",
    "conversation_history":"Το ιστορικό συνομιλιών μου",
    "manual_mode_text":"Χειροκίνητη λειτουργία",
    "automatic_mode_text":"Αυτόματη λειτουργία",
    "manual_mode_description":"Πατήστε το κουμπί μικροφώνου κάτω για να μιλήσετε.",
    "automatic_mode_description":"Μπορείτε να μιλήσετε τώρα, περιμένετε την απάντηση και μετά αρχίστε να μιλάτε ξανά.",
    "messages":"Μηνύματα",
    "evaluate_conversation":"Αξιολόγηση συνομιλίας",
    "premium_notice":"Πρέπει να είστε premium χρήστης. Οι αξιολογήσεις έχουν κόστος για εμάς, οπότε δεν είναι δυνατή η χρήση τους δωρεάν.",
    "see_options":"Δείτε επιλογές",
    "please_choose_language_to_learn":"Η γλώσσα που μαθαίνετε αυτή τη στιγμή:",
    "learn_according_level":"Μάθετε σύμφωνα με το επίπεδό σας",
    "choose_level":"Επιλέξτε το επίπεδό σας",
    "select_level_message":"Παρακαλώ επιλέξτε το επίπεδο που θέλετε να μάθετε:",
    "basic_level":"Βασικό Επίπεδο",
    "intermediate_level":"Μεσαίο Επίπεδο",
    "advanced_level":"Προχωρημένο Επίπεδο",
    "custom_prompt":"Προσαρμοσμένο Θέμα",
    "custom_prompt_description":"Χρησιμοποιήστε αυτό για να εξασκήσετε καθημερινές καταστάσεις, όπως σε έναν φούρνο, σε ένα εστιατόριο ή σε οποιοδήποτε άλλο σενάριο, καθορίζοντας όσο το δυνατόν περισσότερα.",
    "interview_training":"Εκπαίδευση Συνέντευξης",
    "interview_training_description":"Εισαγάγετε τη θέση στο πεδίο παρακάτω, και καλή εξάσκηση!",
    "premium_required":"Απαιτείται Premium",
    "premium_required_message":"Πρέπει να είστε premium χρήστης για να έχετε πρόσβαση σε αυτήν τη λειτουργία.",
    "fetching_products":"Ανάκτηση προϊόντων...",
    "subscriptions":"Συνδρομές",
    "no_cost_option":"Χωρίς κόστος επιλογή:",
    "free_user_with_ads":"Δωρεάν χρήστης με διαφημίσεις",
    "say_goodbye_to_ads":"Αποχαιρετήστε τις διαφημίσεις! Βασιζόμαστε σε μια μικρή ετήσια χρέωση για να καλύψουμε τα έξοδα του διακομιστή και να βελτιώσουμε την εμπειρία σας.",
    "monthly_price":"Μηνιαία τιμή:",
    "free_trial_description":"5 ημέρες δωρεάν δοκιμή, χωρίς διαφημίσεις, όλες οι λειτουργίες διαθέσιμες. Μπορείτε να ακυρώσετε πριν λήξει η δοκιμή."
  },
  "ar_sa":{
    "short":"ar",
    "flag":"sa",
    "complete":"ar-SA",
    "name":"العربية",
    "variant":"ar-SA",
    "free_conversation":"محادثة",
    "job_interview":"مقابلة عمل",
    "choose_subject":"اختر موضوعًا",
    "choose_language":"اختر لغتك",
    "choose_username":"أدخل اسم المستخدم الخاص بك",
    "username":"اسم المستخدم",
    "proceed":"استمر",
    "please_enter_username":"الرجاء إدخال اسم المستخدم الخاص بك.",
    "please_choose_language":"الرجاء اختيار اللغة.",
    "listening_status":"الاستماع",
    "wait_status":"انتظر...",
    "speaking_status":"التحدث",
    "waiting_your_answer_status":"في انتظار إجابتك",
    "tap_mic":"اضغط على الميكروفون للتحدث...",
    "conversation_history":"سجل محادثاتي",
    "manual_mode_text":"الوضع اليدوي",
    "automatic_mode_text":"الوضع التلقائي",
    "manual_mode_description":"اضغط على زر الميكروفون أدناه للتحدث.",
    "automatic_mode_description":"يمكنك الآن التحدث، انتظر الرد ثم ابدأ التحدث مرة أخرى.",
    "messages":"الرسائل",
    "evaluate_conversation":"تقييم المحادثة",
    "premium_notice":"يجب أن تكون مستخدمًا مميزًا؛ التقييمات لها تكلفة علينا، لذلك لا يمكن استخدامها مجانًا.",
    "see_options":"عرض الخيارات",
    "please_choose_language_to_learn":"اللغة التي تتعلمها في الوقت الحالي:",
    "learn_according_level":"تعلم وفقًا لمستواك",
    "choose_level":"اختر مستواك",
    "select_level_message":"الرجاء تحديد المستوى الذي تريد تعلمه:",
    "basic_level":"المستوى الأساسي",
    "intermediate_level":"المستوى المتوسط",
    "advanced_level":"المستوى المتقدم",
    "custom_prompt":"موجه مخصص",
    "custom_prompt_description":"استخدم هذا لممارسة المواقف اليومية، مثل في المخبز، في المطعم، أو في أي سيناريو آخر، مع التحديد قدر الإمكان.",
    "interview_training":"تدريب المقابلة",
    "interview_training_description":"أدخل الوظيفة في الحقل أدناه، وحظًا سعيدًا في التدريب!",
    "premium_required":"مطلوب مميز",
    "premium_required_message":"يجب أن تكون مستخدمًا مميزًا للوصول إلى هذه الميزة.",
    "fetching_products":"جارٍ استرداد المنتجات...",
    "subscriptions":"الاشتراكات",
    "no_cost_option":"خيار بدون تكلفة:",
    "free_user_with_ads":"مستخدم مجاني مع إعلانات",
    "say_goodbye_to_ads":"قل وداعًا للإعلانات! نحن نعتمد على رسوم سنوية صغيرة لتغطية تكاليف الخادم وتحسين تجربتك.",
    "monthly_price":"السعر الشهري:",
    "free_trial_description":"تجربة مجانية لمدة 5 أيام، بدون إعلانات، جميع الميزات متاحة. يمكنك الإلغاء قبل انتهاء الفترة التجريبية."
  },
  "km_kh":{
    "short":"km",
    "flag":"kh",
    "complete":"km-KH",
    "name":"ភាសាខ្មែរ",
    "variant":"km-KH",
    "free_conversation":"ការសន្ទនា",
    "job_interview":"ការសម្ភាសការងារ",
    "choose_subject":"ជ្រើសរើសប្រធានបទ",
    "choose_language":"ជ្រើសរើសភាសារបស់អ្នក",
    "choose_username":"បញ្ចូលឈ្មោះអ្នកប្រើ",
    "username":"ឈ្មោះអ្នកប្រើ",
    "proceed":"បន្ត",
    "please_enter_username":"សូមបញ្ចូលឈ្មោះអ្នកប្រើ។",
    "please_choose_language":"សូមជ្រើសរើសភាសា។",
    "listening_status":"ការស្តាប់",
    "wait_status":"សូមរង់ចាំ...",
    "speaking_status":"ការនិយាយ",
    "waiting_your_answer_status":"រង់ចាំចម្លើយរបស់អ្នក",
    "tap_mic":"ចុចលើមីក្រូហ្វូនដើម្បីនិយាយ...",
    "conversation_history":"ប្រវត្តិការសន្ទនា​របស់ខ្ញុំ",
    "manual_mode_text":"របៀបសៀល",
    "automatic_mode_text":"របៀបស្វ័យប្រវត្តិ",
    "manual_mode_description":"ចុចប៊ូតុងមីក្រូហ្វូននៅខាងក្រោមដើម្បីនិយាយ។",
    "automatic_mode_description":"អ្នកអាចនិយាយឥឡូវនេះ រង់ចាំចម្លើយ ហើយចាប់ផ្តើមនិយាយម្តងទៀត។",
    "messages":"សារជូនដំណឹង",
    "evaluate_conversation":"វាយតម្លៃការសន្ទនា",
    "premium_notice":"អ្នកត្រូវតែជាអ្នកប្រើប្រាស់ឈានមុខ ជាមួយនឹងការវាយតម្លៃទាំងនេះមានតម្លៃសម្រាប់យើង ដូច្នេះវាមិនអាចប្រើប្រាស់ដោយឥតគិតថ្លៃ។",
    "see_options":"មើលជម្រើស",
    "please_choose_language_to_learn":"ភាសាដែលអ្នកកំពុងសិក្សាឥឡូវនេះ៖",
    "learn_according_level":"សិក្សាតាមកម្រិតរបស់អ្នក",
    "choose_level":"ជ្រើសរើសកម្រិតរបស់អ្នក",
    "select_level_message":"សូមជ្រើសរើសកម្រិតដែលអ្នកចង់រៀន៖",
    "basic_level":"កម្រិតមូលដ្ឋាន",
    "intermediate_level":"កម្រិតមធ្យម",
    "advanced_level":"កម្រិតខ្ពស់",
    "custom_prompt":"ប្រធានបទប្តូរតាមបំណង",
    "custom_prompt_description":"ប្រើវាជាឧបករណ៍សម្រាប់អនុវត្តស្ថានភាពប្រចាំថ្ងៃ ដូចជាឃ្លាំងស្តុកអីវ៉ាន់នៅក្នុងបារីយាន្តនិងកន្លែងផ្សេងៗទៀត សូមបញ្ជាក់ច្រើនជាងនេះ។",
    "interview_training":"ការបណ្តុះបណ្តាលសម្ភាសន៍",
    "interview_training_description":"បញ្ចូលមុខងារនៅខាងក្រោម និងសូមសំណាងអញ្ជើញទៀត។",
    "premium_required":"ត្រូវការ​សេវាកម្មដល់មុន",
    "premium_required_message":"អ្នកត្រូវតែជាអ្នកប្រើប្រាស់ឈានមុខ ដើម្បីចូលប្រើមុខងារនេះ។",
    "fetching_products":"ការទាញយកផលិតផល...",
    "subscriptions":"ការជាវសេវាកម្ម",
    "no_cost_option":"ជម្រើសបញ្ចាក់មិនគិតថ្លៃ",
    "free_user_with_ads":"អ្នកប្រើប្រាស់ឥតគិតថ្លៃ មានការផ្សាយពាណិជ្ជកម្ម",
    "say_goodbye_to_ads":"សូមលាបភ្លៀងទៅជាផ្សាយពាណិជ្ជកម្ម! យើងពឹងផ្អែកលើការប្រាក់ខួបដើម្បីបង់តម្លៃសេវាកម្ម និងប្រសើរឡើងការប្រើប្រាស់របស់អ្នក។",
    "monthly_price":"តម្លៃប្រចាំខែ៖",
    "free_trial_description":"សាកល្បងដោយឥតគិតថ្លៃរយៈពេល ៥ ថ្ងៃ មិនមានការផ្សាយពាណិជ្ជកម្ម ផ្សេងៗទៀត។ អ្នកអាចលុបចោលមុនពេលការសាកល្បងបញ្ចប់។"
  },
  "th_th":{
    "short":"th",
    "flag":"th",
    "complete":"th-TH",
    "name":"ไทย",
    "variant":"th-TH",
    "free_conversation":"การสนทนา",
    "job_interview":"การสัมภาษณ์งาน",
    "choose_subject":"เลือกหัวข้อ",
    "choose_language":"เลือกภาษาของคุณ",
    "choose_username":"ป้อนชื่อผู้ใช้ของคุณ",
    "username":"ชื่อผู้ใช้",
    "proceed":"ดำเนินการต่อ",
    "please_enter_username":"กรุณาใส่ชื่อผู้ใช้ของคุณ",
    "please_choose_language":"กรุณาเลือกภาษา",
    "listening_status":"กำลังฟัง",
    "wait_status":"กรุณารอสักครู่...",
    "speaking_status":"กำลังพูด",
    "waiting_your_answer_status":"รอคำตอบของคุณ",
    "tap_mic":"แตะที่ไมโครโฟนเพื่อพูด...",
    "conversation_history":"ประวัติการสนทนาของฉัน",
    "manual_mode_text":"โหมดแมนนวล",
    "automatic_mode_text":"โหมดอัตโนมัติ",
    "manual_mode_description":"แตะที่ปุ่มไมโครโฟนด้านล่างเพื่อพูด",
    "automatic_mode_description":"คุณสามารถพูดได้แล้ว รอคำตอบแล้วเริ่มพูดอีกครั้ง",
    "messages":"ข้อความ",
    "evaluate_conversation":"ประเมินการสนทนา",
    "premium_notice":"คุณต้องเป็นผู้ใช้พรีเมียม การประเมินมีค่าใช้จ่ายสำหรับเรา ดังนั้นจึงไม่สามารถใช้งานได้ฟรี",
    "see_options":"ดูตัวเลือก",
    "please_choose_language_to_learn":"ภาษาที่คุณกำลังเรียนรู้ในขณะนี้:",
    "learn_according_level":"เรียนรู้ตามระดับของคุณ",
    "choose_level":"เลือกระดับของคุณ",
    "select_level_message":"กรุณาเลือกระดับที่คุณต้องการเรียน:",
    "basic_level":"ระดับพื้นฐาน",
    "intermediate_level":"ระดับกลาง",
    "advanced_level":"ระดับสูง",
    "custom_prompt":"ข้อความที่กำหนดเอง",
    "custom_prompt_description":"ใช้สิ่งนี้เพื่อฝึกฝนสถานการณ์ในชีวิตประจำวัน เช่น ในร้านเบเกอรี่ ในร้านอาหาร หรือในสถานการณ์อื่นๆ โดยระบุให้มากที่สุดเท่าที่จะทำได้",
    "interview_training":"การฝึกสัมภาษณ์",
    "interview_training_description":"ป้อนตำแหน่งในฟิลด์ด้านล่างและโชคดีในการฝึก!",
    "premium_required":"ต้องมีพรีเมียม",
    "premium_required_message":"คุณต้องเป็นผู้ใช้พรีเมียมเพื่อเข้าถึงฟีเจอร์นี้",
    "fetching_products":"กำลังดึงข้อมูลผลิตภัณฑ์...",
    "subscriptions":"การสมัครรับข้อมูล",
    "no_cost_option":"ไม่มีค่าใช้จ่าย:",
    "free_user_with_ads":"ผู้ใช้ฟรีที่มีโฆษณา",
    "say_goodbye_to_ads":"บอกลาโฆษณา! เราพึ่งพาค่าธรรมเนียมรายปีเล็กน้อยเพื่อครอบคลุมค่าใช้จ่ายของเซิร์ฟเวอร์และปรับปรุงประสบการณ์ของคุณ",
    "monthly_price":"ราคาต่อเดือน:",
    "free_trial_description":"ทดลองใช้งานฟรี 5 วัน ไม่มีโฆษณา ฟีเจอร์ทั้งหมดใช้งานได้ คุณสามารถยกเลิกก่อนที่การทดลองใช้จะสิ้นสุด"
  },
  "ko_kr":{
    "short":"ko",
    "flag":"kr",
    "complete":"ko-KR",
    "name":"한국어",
    "variant":"ko-KR",
    "free_conversation":"대화",
    "job_interview":"면접",
    "choose_subject":"주제 선택",
    "choose_language":"언어를 선택하세요",
    "choose_username":"사용자 이름을 입력하세요",
    "username":"사용자 이름",
    "proceed":"계속",
    "please_enter_username":"사용자 이름을 입력하세요.",
    "please_choose_language":"언어를 선택하세요.",
    "listening_status":"듣는 중",
    "wait_status":"기다려주세요...",
    "speaking_status":"말하기",
    "waiting_your_answer_status":"당신의 대답을 기다리는 중",
    "tap_mic":"말하려면 마이크를 탭하세요...",
    "conversation_history":"내 대화 기록",
    "manual_mode_text":"수동 모드",
    "automatic_mode_text":"자동 모드",
    "manual_mode_description":"말하려면 아래의 마이크 버튼을 누르세요.",
    "automatic_mode_description":"이제 말할 수 있습니다. 응답을 기다리고 다시 말하기 시작하세요.",
    "messages":"메시지",
    "evaluate_conversation":"대화 평가",
    "premium_notice":"프리미엄 사용자여야 합니다. 평가에는 비용이 들기 때문에 무료로 사용할 수 없습니다.",
    "see_options":"옵션 보기",
    "please_choose_language_to_learn":"현재 배우고 있는 언어:",
    "learn_according_level":"자신의 수준에 맞춰 배우세요",
    "choose_level":"수준 선택",
    "select_level_message":"배우고 싶은 수준을 선택하세요:",
    "basic_level":"기초 수준",
    "intermediate_level":"중급 수준",
    "advanced_level":"고급 수준",
    "custom_prompt":"맞춤 프롬프트",
    "custom_prompt_description":"이것을 사용하여 빵집, 레스토랑 등 일상 상황을 연습하세요. 가능한 한 구체적으로 명시하세요.",
    "interview_training":"면접 훈련",
    "interview_training_description":"아래 필드에 직위를 입력하고, 연습을 즐기세요!",
    "premium_required":"프리미엄 필요",
    "premium_required_message":"이 기능에 접근하려면 프리미엄 사용자여야 합니다.",
    "fetching_products":"제품 가져오는 중...",
    "subscriptions":"구독",
    "no_cost_option":"비용 없음:",
    "free_user_with_ads":"광고가 있는 무료 사용자",
    "say_goodbye_to_ads":"광고와 작별하세요! 서버 비용을 충당하고 경험을 개선하기 위해 소액의 연간 요금에 의존합니다.",
    "monthly_price":"월 가격:",
    "free_trial_description":"광고 없이 5일 무료 체험, 모든 기능 이용 가능. 체험 종료 전에 취소할 수 있습니다."
  },
  "vi_vn":{
    "short":"vi",
    "flag":"vn",
    "complete":"vi-VN",
    "name":"Tiếng Việt",
    "variant":"vi-VN",
    "free_conversation":"Cuộc trò chuyện",
    "job_interview":"Phỏng vấn xin việc",
    "choose_subject":"Chọn chủ đề",
    "choose_language":"Chọn ngôn ngữ của bạn",
    "choose_username":"Nhập tên người dùng của bạn",
    "username":"Tên người dùng",
    "proceed":"Tiếp tục",
    "please_enter_username":"Vui lòng nhập tên người dùng của bạn.",
    "please_choose_language":"Vui lòng chọn ngôn ngữ.",
    "listening_status":"Đang lắng nghe",
    "wait_status":"Đợi đã...",
    "speaking_status":"Đang nói",
    "waiting_your_answer_status":"Đang chờ câu trả lời của bạn",
    "tap_mic":"Chạm vào mic để nói...",
    "conversation_history":"Lịch sử trò chuyện của tôi",
    "manual_mode_text":"Chế độ thủ công",
    "automatic_mode_text":"Chế độ tự động",
    "manual_mode_description":"Chạm vào nút mic bên dưới để nói.",
    "automatic_mode_description":"Bây giờ bạn có thể nói, chờ đợi câu trả lời và sau đó bắt đầu nói lại.",
    "messages":"Tin nhắn",
    "evaluate_conversation":"Đánh giá cuộc trò chuyện",
    "premium_notice":"Bạn cần phải là người dùng cao cấp; các đánh giá có chi phí cho chúng tôi, vì vậy không thể sử dụng chúng miễn phí.",
    "see_options":"Xem tùy chọn",
    "please_choose_language_to_learn":"Ngôn ngữ bạn đang học:",
    "learn_according_level":"Học theo cấp độ của bạn",
    "choose_level":"Chọn cấp độ của bạn",
    "select_level_message":"Vui lòng chọn cấp độ bạn muốn học:",
    "basic_level":"Cấp độ cơ bản",
    "intermediate_level":"Cấp độ trung cấp",
    "advanced_level":"Cấp độ nâng cao",
    "custom_prompt":"Lời nhắc tùy chỉnh",
    "custom_prompt_description":"Sử dụng điều này để thực hành các tình huống hàng ngày, chẳng hạn như trong một tiệm bánh, trong một nhà hàng hoặc bất kỳ tình huống nào khác, chỉ định càng nhiều càng tốt.",
    "interview_training":"Đào tạo phỏng vấn",
    "interview_training_description":"Nhập vị trí trong trường bên dưới, và chúc may mắn trong việc thực hành!",
    "premium_required":"Yêu cầu cao cấp",
    "premium_required_message":"Bạn cần phải là người dùng cao cấp để truy cập tính năng này.",
    "fetching_products":"Đang tải sản phẩm...",
    "subscriptions":"Đăng ký",
    "no_cost_option":"Không tốn chi phí:",
    "free_user_with_ads":"Người dùng miễn phí với quảng cáo",
    "say_goodbye_to_ads":"Hãy nói lời tạm biệt với quảng cáo! Chúng tôi dựa vào một khoản phí hàng năm nhỏ để trang trải chi phí máy chủ và cải thiện trải nghiệm của bạn.",
    "monthly_price":"Giá hàng tháng:",
    "free_trial_description":"Dùng thử miễn phí 5 ngày, không quảng cáo, tất cả các tính năng có sẵn. Bạn có thể hủy trước khi hết thời gian dùng thử."
  },
  "tr_tr":{
    "short":"tr",
    "flag":"tr",
    "complete":"tr-TR",
    "name":"Türkçe",
    "variant":"tr-TR",
    "free_conversation":"Konuşma",
    "job_interview":"İş Görüşmesi",
    "choose_subject":"Bir Konu Seçin",
    "choose_language":"Dilinizi Seçin",
    "choose_username":"Kullanıcı Adınızı Girin",
    "username":"Kullanıcı Adı",
    "proceed":"Devam et",
    "please_enter_username":"Lütfen kullanıcı adınızı girin.",
    "please_choose_language":"Lütfen bir dil seçin.",
    "listening_status":"Dinleme",
    "wait_status":"Bekleyin...",
    "speaking_status":"Konuşma",
    "waiting_your_answer_status":"Cevabınızı Bekliyor",
    "tap_mic":"Konuşmak için mikrofona dokunun...",
    "conversation_history":"Konuşma Geçmişim",
    "manual_mode_text":"Manuel Mod",
    "automatic_mode_text":"Otomatik Mod",
    "manual_mode_description":"Konuşmak için aşağıdaki mikrofon düğmesine dokunun.",
    "automatic_mode_description":"Şimdi konuşabilirsiniz, cevabı bekleyin ve tekrar konuşmaya başlayın.",
    "messages":"Mesajlar",
    "evaluate_conversation":"Konuşmayı Değerlendir",
    "premium_notice":"Premium kullanıcı olmalısınız; değerlendirmeler bizim için maliyetlidir, bu nedenle bunları ücretsiz kullanmak mümkün değildir.",
    "see_options":"Seçenekleri Gör",
    "please_choose_language_to_learn":"Şu anda öğrendiğiniz dil:",
    "learn_according_level":"Seviyenize göre öğrenin",
    "choose_level":"Seviyenizi Seçin",
    "select_level_message":"Lütfen öğrenmek istediğiniz seviyeyi seçin:",
    "basic_level":"Temel Seviye",
    "intermediate_level":"Orta Seviye",
    "advanced_level":"İleri Seviye",
    "custom_prompt":"Özel İstek",
    "custom_prompt_description":"Bu, günlük durumları, örneğin bir fırında, bir restoranda veya başka herhangi bir senaryoda, olabildiğince fazla belirterek pratik yapmak için kullanılır.",
    "interview_training":"Mülakat Eğitimi",
    "interview_training_description":"Aşağıdaki alana pozisyonu girin ve iyi pratikler!",
    "premium_required":"Premium Gerekli",
    "premium_required_message":"Bu özelliğe erişmek için premium kullanıcı olmanız gerekiyor.",
    "fetching_products":"Ürünler alınıyor...",
    "subscriptions":"Abonelikler",
    "no_cost_option":"Maliyet Yok Seçeneği:",
    "free_user_with_ads":"Reklamlı Ücretsiz Kullanıcı",
    "say_goodbye_to_ads":"Reklamlara elveda deyin! Sunucu maliyetlerini karşılamak ve deneyiminizi geliştirmek için küçük bir yıllık ücrete güveniyoruz.",
    "monthly_price":"Aylık fiyat:",
    "free_trial_description":"5 gün ücretsiz deneme, reklam yok, tüm özellikler kullanılabilir. Deneme süresi dolmadan iptal edebilirsiniz."
  },
  "he_il": {
  "short": "he",
  "flag": "il",
  "complete": "he-IL",
  "name": "עברית",
  "variant": "he-IL",
  "free_conversation": "שיחה חופשית",
  "job_interview": "ראיון עבודה",
  "choose_subject": "בחר נושא מותאם אישית",
  "choose_language": "בחר את השפה שלך",
  "choose_username": "הזן את שם המשתמש שלך",
  "username": "שם משתמש",
  "proceed": "המשך",
  "please_enter_username": "אנא הזן את שם המשתמש שלך.",
  "please_choose_language": "אנא בחר שפה.",
  "listening_status": "האזנה",
  "wait_status": "המתן...",
  "speaking_status": "דיבור",
  "waiting_your_answer_status": "מחכה לתשובה שלך",
  "tap_mic": "הקש על המיקרופון כדי לדבר...",
  "conversation_history": "היסטוריית השיחות שלי",
  "manual_mode_text": "מצב ידני",
  "automatic_mode_text": "מצב אוטומטי",
  "manual_mode_description": "הקש על כפתור המיקרופון למטה כדי לדבר.",
  "automatic_mode_description":
      "אתה יכול לדבר עכשיו, המתן לתשובה והתחל לדבר שוב.",
  "messages": "הודעות",
  "evaluate_conversation": "הערך את השיחה",
  "premium_notice":
      "עליך להיות משתמש פרימיום; הערכות עולות לנו, ולכן לא ניתן להשתמש בהן בחינם.",
  "see_options": "ראה אפשרויות",
  "please_choose_language_to_learn":
      "השפה שאתה לומד כרגע:",
  "learn_according_level": "למד בהתאם לרמתך",
  "choose_level": "בחר את הרמה שלך",
  "select_level_message":
      "אנא בחר את הרמה שברצונך ללמוד:",
  "basic_level": "רמה בסיסית",
  "intermediate_level": "רמה בינונית",
  "advanced_level": "רמה מתקדמת",
  "custom_prompt": "הנחיה מותאמת אישית",
  "custom_prompt_description":
      "השתמש בזה כדי לתרגל מצבים יומיומיים, כמו במאפייה, במסעדה, או כל תרחיש אחר, ציין כמה שיותר.",
  "interview_training": "אימון לראיון",
  "interview_training_description":
      "הזן את התפקיד בשדה למטה, ובהצלחה!",
  "premium_required": "נדרש פרימיום",
  "premium_required_message":
      "עליך להיות משתמש פרימיום כדי לגשת לתכונה זו.",
  "fetching_products": "מביא מוצרים...",
  "subscriptions": "מנויים",
  "no_cost_option": "אפשרות ללא עלות:",
  "free_user_with_ads": "משתמש חינמי עם פרסומות",
  "say_goodbye_to_ads":
      "אמור שלום לפרסומות! אנו מסתמכים על תשלום שנתי קטן כדי לכסות את עלויות השרת ולשפר את החוויה שלך.",
  "monthly_price": "מחיר חודשי:",
  "free_trial_description":
      "5 ימי ניסיון חינם, ללא פרסומות, כל התכונות זמינות. ניתן לבטל לפני תום הניסיון."
},
"bg_bg": {
  "short": "bg",
  "flag": "bg",
  "complete": "bg-BG",
  "name": "Български",
  "variant": "bg-BG",
  "free_conversation": "Разговор",
  "job_interview": "Интервю за работа",
  "choose_subject": "Изберете тема",
  "choose_language": "Изберете вашия език",
  "choose_username": "Въведете вашето потребителско име",
  "username": "Потребителско име",
  "proceed": "Продължете",
  "please_enter_username": "Моля, въведете вашето потребителско име.",
  "please_choose_language": "Моля, изберете език.",
  "listening_status": "Слушане",
  "wait_status": "Изчакайте...",
  "speaking_status": "Говорене",
  "waiting_your_answer_status": "Изчакване на вашия отговор",
  "tap_mic": "Докоснете микрофона, за да говорите...",
  "conversation_history": "История на разговорите",
  "manual_mode_text": "Ръчен режим",
  "automatic_mode_text": "Автоматичен режим",
  "manual_mode_description": "Докоснете бутона на микрофона по-долу, за да говорите.",
  "automatic_mode_description": "Можете да говорите сега, изчакайте отговора и след това говорете отново.",
  "messages": "Съобщения",
  "evaluate_conversation": "Оценка на разговора",
  "premium_notice": "Трябва да бъдете премиум потребител; оценките имат разходи за нас, така че не е възможно да ги използвате безплатно.",
  "see_options": "Вижте опциите",
  "please_choose_language_to_learn": "Езикът, който в момента учите:",
  "learn_according_level": "Учете според вашето ниво",
  "choose_level": "Изберете вашето ниво",
  "select_level_message": "Моля, изберете нивото, което искате да учите:",
  "basic_level": "Основно ниво",
  "intermediate_level": "Средно ниво",
  "advanced_level": "Напреднало ниво",
  "custom_prompt": "Персонализирана тема",
  "custom_prompt_description": "Използвайте това, за да практикувате ежедневни ситуации, като в пекарна, в ресторант или в друг сценарий, като определите колкото е възможно повече.",
  "interview_training": "Обучение за интервю",
  "interview_training_description": "Въведете позицията в полето по-долу и добър късмет!",
  "premium_required": "Необходимо е премиум",
  "premium_required_message": "Трябва да бъдете премиум потребител, за да имате достъп до тази функция.",
  "fetching_products": "Извличане на продукти...",
  "subscriptions": "Абонаменти",
  "no_cost_option": "Безплатна опция:",
  "free_user_with_ads": "Безплатен потребител с реклами",
  "say_goodbye_to_ads": "Кажете сбогом на рекламите! Ние разчитаме на малка годишна такса, за да покрием разходите за сървъра и да подобрим вашия опит.",
  "monthly_price": "Месечна цена:",
  "free_trial_description": "5 дни безплатен пробен период, без реклами, всички функции са достъпни. Можете да отмените преди изтичане на пробния период."
}
}