{
  "en_us": {
    "short": "en",
    "flag": "us",
    "complete": "en-US",
    "name": "English",
    "variant": "en-US",
    "free_conversation": "Conversation",
    "job_interview": "Job Interview",
    "choose_subject": "Choose a Custom Subject",
    "choose_language": "Choose Your Language",
    "choose_username": "Enter Your Username",
    "username": "Username",
    "proceed": "Continue",
    "please_enter_username": "Please enter your username.",
    "please_choose_language": "Please select a language.",
    "listening_status": "Listening",
    "wait_status": "Wait...",
    "speaking_status": "Speaking",
    "waiting_your_answer_status": "Waiting your answer",
    "tap_mic": "Tap on the mic to speak...",
    "conversation_history": "My conversation history",
    "manual_mode_text": "Manual Mode",
    "automatic_mode_text": "Automatic Mode",
    "manual_mode_description": "Tap on the mic button on the bottom to speak.",
    "automatic_mode_description":
      "You can speak now, after that await the response, and start speak again, try that.",
    "messages": "Messages",
    "evaluate_conversation": "Evaluate Conversation",
    "premium_notice":
      "You need to be a premium user; the evaluations have a cost for us, so it's not possible to use them for free.",
    "see_options": "See options",
    "please_choose_language_to_learn": "The language you are learning at the moment:",
    "learn_according_level": "Learn according to your level",
    "choose_level": "Choose Your Level",
    "select_level_message": "Please select the level you want to learn:",
    "basic_level": "Basic Level",
    "intermediate_level": "Intermediate Level",
    "advanced_level": "Advanced Level",
    "custom_prompt": "Custom Prompt",
    "custom_prompt_description":
      "Use this to practice everyday situations, like in a bakery, in a restaurant, or any other scenario, specifying as much as possible.",
    "interview_training": "Interview Training",
    "interview_training_description":
      "Enter the position in the field below, and good practice!",
    "premium_required": "Premium Required",
    "premium_required_message":
      "You need to be a premium user to access this feature.",
    "fetching_products": "Fetching products...",
    "subscriptions": "Subscriptions",
    "no_cost_option": "No costs option:",
    "free_user_with_ads": "Free user with ads",
    "say_goodbye_to_ads":
      "Say goodbye to ads! We rely on a small yearly fee to cover server costs and improve your experience.",
    "monthly_price": "Monthly price:",
    "free_trial_description":
      "5 days free trial, no ads, all features available. You can cancel before the trial ends."
  },
  "pt_br": {
    "short": "pt",
    "flag": "br",
    "complete": "pt-BR",
    "name": "Português",
    "variant": "pt-BR",
    "free_conversation": "Conversar livremente",
    "job_interview": "Entrevista de emprego",
    "choose_subject": "Escolha um tema",
    "choose_language": "Escolha seu idioma",
    "choose_username": "Seu nome",
    "username": "Nome de usuário",
    "proceed": "Continuar",
    "please_enter_username": "Digite o nome de usuário.",
    "please_choose_language": "Selecione o idioma.",
    "listening_status": "Ouvindo",
    "wait_status": "Aguarde...",
    "speaking_status": "Falando",
    "waiting_your_answer_status": "Aguardando sua resposta",
    "tap_mic": "Clique no microfone para falar...",
    "conversation_history": "Meu histórico de conversação",
    "manual_mode_text": "Modo Manual",
    "automatic_mode_text": "Modo Automático",
    "manual_mode_description":
        "Clique no microfone na parte inferior para falar.",
    "automatic_mode_description":
        "Você pode falar agora, aguarde a resposta e comece a falar novamente, tente.",
    "messages": "Mensagens",
    "evaluate_conversation": "Avaliar esta conversa",
    "premium_notice":
        "Você precisa ser um usuário premium; as avaliações têm um custo para nós, então não é possível usá-las gratuitamente.",
    "see_options": "Ver opções",
    "please_choose_language_to_learn": "Qual idioma quer praticar?",
    "learn_according_level": "Aprenda de acordo com seu nível",
    "choose_level": "Escolha seu nível",
    "select_level_message": "Por favor, selecione o nível que deseja aprender:",
    "basic_level": "Nível Básico",
    "intermediate_level": "Nível Intermediário",
    "advanced_level": "Nível Avançado",
    "custom_prompt": "Tema Personalizado",
    "custom_prompt_description":
        "Use para praticar situações cotidianas, como exemplo: em uma padaria, em um restaurante ou qualquer outro tema, especificando ao máximo.",
    "interview_training": "Treinamento para entrevista",
    "interview_training_description":
        "Escreva o cargo no campo abaixo, e boa prática!",
    "premium_required": "Requerido Premium",
    "premium_required_message":
        "Você precisa ser um usuário premium para acessar este recurso.",
    "fetching_products": "Buscando produtos...",
    "subscriptions": "Assinaturas",
    "no_cost_option": "Opção sem custos:",
    "free_user_with_ads": "Usuário gratuito com anúncios",
    "say_goodbye_to_ads":
        "Diga adeus aos anúncios! Contamos com uma pequena taxa anual para cobrir os custos do servidor e melhorar sua experiência.",
    "monthly_price": "Preço mensal:",
    "free_trial_description":
        "5 dias de teste grátis, sem anúncios, todos os recursos disponíveis. Você pode cancelar antes que o teste termine."
  }
}